# Bluetooth power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Split stability
CONFIG_ZMK_SPLIT_BLE=y
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN is not set

# Debounce (un poco más seguro que 1ms)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Sleep desactivado para evitar problemas de reconexión
# CONFIG_ZMK_SLEEP is not set