name: Build ZMK firmware
on:
  push:
    branches:
      - main  # Cambios en la rama 'main'
  pull_request:
    branches:
      - main  # PRs dirigidos a la rama 'main'
  workflow_dispatch:  # Permite ejecución manual desde GitHub UI

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.1  # Aquí se usa el flujo de trabajo predefinido del repositorio de ZMK